<a href="https://colab.research.google.com/github/kubendran389-png/Hospital-Patient-Data-Analysis/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **ERROR** **HANDLING**


In [ ]:
#error hanling

try:
  n = int(input("Enter a number:"))
  print(n)

except:
  print("Invalid input")

Enter a number:HK
Invalid input


# **NUMPY**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5]) #1D arr
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([[1,2],[2,4]]) #2D arr
print(arr)

[[1 2]
 [2 4]]


In [ ]:
import numpy as np
arr = np.array([[[1,2],[2,4]],[[3,5],[6,7]]]) #3D arr
print(arr)

[[[1 2]
  [2 4]]

 [[3 5]
  [6 7]]]


# **ARRAY OPERATION**

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

#addition
c = a+b
print(c)

#multiplication
d= a*b
print(d)

#power
e = a**2
print(e)

#sqrt
f = np.sqrt(a)
print(f)

#sum
g = np.sum(a)
print(g)

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
6
