<a href="https://colab.research.google.com/github/kubendran389-png/Hospital-Patient-Data-Analysis/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INDEXING & SLICING**

In [ ]:
import numpy as np
marks = np.array([90,80,75,60,100])
print(marks[1:4])

[80 75 60]


# **Reshape & Transpose**

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)

print(b)

c= b.transpose()
print("\n",c)


[[1 2 3]
 [4 5 6]]

 [[1 4]
 [2 5]
 [3 6]]


# **Aggregation & Axis Operation**

In [ ]:
#sum() --> total

import numpy as np

a = np.array([1,2,3,4,5,6])
total = np.sum(a)
print(total)

21


In [ ]:
#mean --> average

import numpy as np

a = np.array([6,2,1,6,3,9])
avg = np.mean(a)
print(avg)

4.5


In [ ]:
#median() --> middle value when sorted

import numpy as np

a = np.array([6,2,1,6,3,9])
median = np.median(a)
print(median)

4.5
